title:              "빈채"
tagline:            "빈칸을 채워주세요"
email:              "fkwpsrk935@naver.com"
description:        "마케팅, 광고, 도서 리뷰, 이슈 등 다양한 정보로 빈칸을 채워보세요."
author:             "김종엽"
baseurl:            "/"
url:                "https://kimjongyeob.github.io/"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
diqus:
  shortname: https://kimjongyeob.github.io/
